name: Github Action Deploy
on:
  push:
    branches: ["master"]
    paths-ignore:
      - "readme.md"
      - ".env"
      - ".gitignore"
      - ".gitmodules"
      - "bin"
# github_token: ${{ secrets.GITHUB_TOKEN }}
permissions:
  contents: write
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Nodejs v18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build Package
        run: |
          yarn install
          npm run build
          cd ./dist
          echo > .nojekyll
          git config user.name zsj1029
          git config user.email zsj1029@gmail.com
          git init
          git checkout -B gh-pages
          git add -A
          git commit -m -'deploy'
          git remote rm origin
          git remote add origin ***github.com/zsj1029/vite-mithril-jsx.git

          git push origin gh-pages
